Fixed importer/exporter

diff --git a/src/devtodo-to-dnt.in b/src/devtodo-to-dnt.in
--- a/src/devtodo-to-dnt.in
+++ b/src/devtodo-to-dnt.in
@@ -2,6 +2,7 @@
 
 #
 # Copyright (C) 2008, 2009 Francesco Salvestrini
+#                          Alessandro Massignan
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,7 +19,7 @@
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
 
-PROGRAM_NAME="`echo $0 | @SED@ 's/^.*\/\([^\/][^\/]*\)$/\1/'`"
+PROGRAM_NAME="devtodo-to-dnt"
 
 DNT_VERSION="@PACKAGE_VERSION@"
 DT_VERSION="@DEVTODO_VERSION@"
@@ -26,12 +27,12 @@ DT_DB_VERSION=""
 XSLT_FILE=""
 
 function hint {
-    echo "${PROGRAM_NAME}: ${1}"
+    echo "${PROGRAM_NAME}: $1"
     echo "Try \`${PROGRAM_NAME} -h' for more information."
 }
 
 function error {
-    echo "${PROGRAM_NAME}: ${1}" > /dev/stderr
+    echo "${PROGRAM_NAME}: $1" > /dev/stderr
 }
 
 function version {
@@ -104,8 +105,8 @@ if test x"${FORCE}" != x"yes" ; then
 fi
 
 if test x"${DT_VERSION}" = x""; then
-   error "Bug hit! Missing devtodo version"
-   exit 1
+    error "Bug hit! Missing devtodo version"
+    exit 1
 fi
 XSLT_FILE="${LIBDIR}/devtodo-${DT_VERSION}-to-dnt.xslt"
 
@@ -115,13 +116,13 @@ if test ! -r "${XSLT_FILE}"; then
 fi
 
 if test x"${DNT_VERSION}" = x""; then
-   error "Bug hit! Missing dnt version"
-   exit 1
+    error "Bug hit! Missing dnt version"
+    exit 1
 fi
 
 : >$OUTPUT || {
-  error "Cannot write \`${OUTPUT}' file"
-  exit 1
+    error "Cannot write \`${OUTPUT}' file"
+    exit 1
 }
 
 DT_DB_VERSION="`@SED@ -n '
@@ -172,9 +173,9 @@ fi
 @XSLTPROC@ \
     --output $OUTPUT \
     $XSLT_FILE $INPUT >/dev/null 2>&1 || {
-      error  "Cannot transform file \`${INPUT}' to file \`${OUTPUT}'"
-      rm -f $OUTPUT 2>/dev/null
-      exit 1
-    }
+    error  "Cannot transform file \`${INPUT}' to file \`${OUTPUT}'"
+    rm -f $OUTPUT 2>/dev/null
+    exit 1
+}
 
 exit 0
diff --git a/src/dnt-to-devtodo.in b/src/dnt-to-devtodo.in
--- a/src/dnt-to-devtodo.in
+++ b/src/dnt-to-devtodo.in
@@ -2,6 +2,7 @@
 
 #
 # Copyright (C) 2008, 2009 Francesco Salvestrini
+#                          Alessandro Massignan
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,19 +19,19 @@
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
 
-PROGRAM_NAME="`echo $0 | @SED@ 's/^.*\/\([^\/][^\/]*\)$/\1/'`"
+PROGRAM_NAME="dnt-to-devtodo"
 
 DNT_VERSION="@PACKAGE_VERSION@"
 DT_VERSION="@DEVTODO_VERSION@"
 XSLT_FILE=""
 
 function hint {
-    echo "${PROGRAM_NAME}: ${1}"
+    echo "${PROGRAM_NAME}: $1"
     echo "Try \`${PROGRAM_NAME} -h' for more information."
 }
 
 function error {
-    echo "${PROGRAM_NAME}: ${1}" > /dev/stderr
+    echo "${PROGRAM_NAME}: $1" > /dev/stderr
 }
 
 function version {
@@ -106,8 +107,8 @@ if test x"${FORCE}" != x"yes" ; then
 fi
 
 if test x"${DT_VERSION}" = x""; then
-   error "Bug hit! Missing devtodo version"
-   exit 1
+    error "Bug hit! Missing devtodo version"
+    exit 1
 fi
 XSLT_FILE="${LIBDIR}/dnt-to-devtodo-${DT_VERSION}.xslt"
 
@@ -117,22 +118,22 @@ if test ! -r "${XSLT_FILE}"; then
 fi
 
 if test x"${DNT_VERSION}" = x""; then
-   error "Bug hit! Missing dnt version"
-   exit 1
+    error "Bug hit! Missing dnt version"
+    exit 1
 fi
 
 : >$OUTPUT || {
-  error "Cannot write \`${OUTPUT}' file"
-  exit 1
+    error "Cannot write \`${OUTPUT}' file"
+    exit 1
 }
 
 @XSLTPROC@ \
     --output $OUTPUT \
     --stringparam dt_version $DT_VERSION \
     $XSLT_FILE $INPUT >/dev/null 2>&1 || {
-      error "Cannot transform file \`${INPUT}' to file \`${OUTPUT}'"
-      rm -f $OUTPUT >/dev/null 2>&1
-      exit 1
-    }
+    error "Cannot transform file \`${INPUT}' to file \`${OUTPUT}'"
+    rm -f $OUTPUT >/dev/null 2>&1
+    exit 1
+}
 
 exit 0
